#ifndef ALOS_PATH_ABI_H
#define ALOS_PATH_ABI_H
#define ALOS_PATH_OPEN 1
#define ALOS_PATH_STAT 2
#define ALOS_PATH_UNLINK 3
#define ALOS_PATH_REALPATH 4
#define ALOS_PATH_CHMOD 5
#define ALOS_PATH_SYMLINK 6
#define ALOS_PATH_READLINK 7
#define ALOS_PATH_RENAME 8
#define ALOS_PATH_NAME_MAX 9
#endif
